name: Build from tarball

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'
  FLAKY_TESTS: keep_retrying

permissions:
  contents: read

jobs:
  build-tarball:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: nodejs/node
          ref: v18.12.1
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Install GCC 8
        run: sudo apt install gcc-8 g++-8
      - name: Make tarball
        run: |
          export C=/usr/bin/gcc-8
          export CXX=/usr/bin/g++-8
          ./configure && make binary -j8 SKIP_XZ=1
          mkdir tarballs
          mv *.tar.gz tarballs
      - name: Upload tarball artifact
        uses: actions/upload-artifact@v3
        with:
          name: tarballs
          path: tarballs
#   test-tarball-linux:
#     needs: build-tarball
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           persist-credentials: false
#       - name: Set up Python ${{ env.PYTHON_VERSION }}
#         uses: actions/setup-python@v3
#         with:
#           python-version: ${{ env.PYTHON_VERSION }}
#       - name: Environment Information
#         run: npx envinfo
#       - name: Download tarball
#         uses: actions/download-artifact@v3
#         with:
#           name: tarballs
#           path: tarballs
#       - name: Extract tarball
#         run: |
#           tar xzf tarballs/*.tar.gz -C $RUNNER_TEMP
#           echo "TAR_DIR=$RUNNER_TEMP/`basename tarballs/*.tar.gz .tar.gz`" >> $GITHUB_ENV
#       - name: Copy directories needed for testing
#         run: |
#           cp -r tools/node_modules $TAR_DIR/tools
#           cp -r tools/eslint-rules $TAR_DIR/tools
#       - name: Build
#         run: |
#           cd $TAR_DIR
#           make build-ci -j2 V=1
#       - name: Test
#         run: |
#           cd $TAR_DIR
#           make run-ci -j2 V=1 TEST_CI_ARGS="-p dots --measure-flakiness 9"
